.. User's Guide
   ------------

ユーザーガイド
---------------

.. This part of the documentation, which is mostly prose, begins with some
   background information about Flask, then focuses on step-by-step
   instructions for web development with Flask.

ドキュメントのこのパートでは、Flaskの生い立ちを説明します。また、Flaskを使用したWeb開発をステップバイステップで紹介します。

.. toctree::
   :maxdepth: 2

   foreword
   installation
   quickstart
   tutorial/index
   templating
   testing
   errorhandling
   config
   signals
   views
   reqcontext
   blueprints
   extensions
   shell
   patterns/index
   deploying/index
   becomingbig

.. API Reference
   -------------

APIリファレンス
----------------

.. If you are looking for information on a specific function, class or
   method, this part of the documentation is for you.

具体的な機能やクラスやメソッドについての情報をさがしているなら、ドキュメントのこのパートが役に立つでしょう。

.. toctree::
   :maxdepth: 2

   api

.. Additional Notes
   ----------------

追加の注意事項
-------------------

.. Design notes, legal information and changelog are here for the interested.

デザインに関する注意や利用規約や変更履歴はここにあります。

.. toctree::
   :maxdepth: 2

   design
   htmlfaq
   security
   unicode
   extensiondev
   styleguide
   upgrading
   changelog
   license
